"""agregar_tablas_notificaciones_y_auditoria

Revision ID: 0337384599f6
Revises: d630ed70cece
Create Date: 2026-08-03 20:29:29.913560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0337384599f6'
down_revision: Union[str, Sequence[str], None] = 'd630ed70cece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_auditoria',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index(op.f('ix_logs_auditoria_id_log'), 'logs_auditoria', ['id_log'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.String(length=255), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_index(op.f('ix_notificaciones_id_notificacion'), 'notificaciones', ['id_notificacion'], unique=False)
    op.create_table('rrhh',
    sa.Column('id_rrhh', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_rrhh')
    )
    op.create_index(op.f('ix_rrhh_id_rrhh'), 'rrhh', ['id_rrhh'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rrhh_id_rrhh'), table_name='rrhh')
    op.drop_table('rrhh')
    op.drop_index(op.f('ix_notificaciones_id_notificacion'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_logs_auditoria_id_log'), table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###
