"""agregar_creador_a_intervenciones

Revision ID: 3be9fdda03f4
Revises: e628e0133ad6
Create Date: 2026-08-05 19:28:28.598824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be9fdda03f4'
down_revision: Union[str, Sequence[str], None] = 'e628e0133ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervenciones', sa.Column('id_usuario_creador', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'intervenciones', 'usuarios', ['id_usuario_creador'], ['id_usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intervenciones', type_='foreignkey')
    op.drop_column('intervenciones', 'id_usuario_creador')
    # ### end Alembic commands ###
