"""agrega token_version a usuarios

Revision ID: 6db0e3030183
Revises: 99afc1f85488
Create Date: 2026-08-13 08:43:28.761199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db0e3030183'
down_revision: Union[str, Sequence[str], None] = '99afc1f85488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('asistio', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('parcial', sa.Integer(), nullable=True),
    sa.Column('promedio', sa.Float(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('estudiantes', sa.Column('dificultad_economica', sa.Integer(), nullable=True))
    op.add_column('estudiantes', sa.Column('trabaja_actualmente', sa.Integer(), nullable=True))
    op.add_column('estudiantes', sa.Column('reporte_emocional', sa.Integer(), nullable=True))
    op.add_column('estudiantes', sa.Column('solicitud_baja', sa.Integer(), nullable=True))
    op.add_column('estudiantes', sa.Column('acceso_tecnologico', sa.String(length=20), nullable=True))
    op.add_column('estudiantes', sa.Column('nivel_riesgo', sa.String(length=10), nullable=True))
    op.add_column('estudiantes', sa.Column('probabilidad_riesgo', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('intervenciones', sa.Column('escalado', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('token_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'token_version')
    op.drop_column('intervenciones', 'escalado')
    op.drop_column('estudiantes', 'probabilidad_riesgo')
    op.drop_column('estudiantes', 'nivel_riesgo')
    op.drop_column('estudiantes', 'acceso_tecnologico')
    op.drop_column('estudiantes', 'solicitud_baja')
    op.drop_column('estudiantes', 'reporte_emocional')
    op.drop_column('estudiantes', 'trabaja_actualmente')
    op.drop_column('estudiantes', 'dificultad_economica')
    op.drop_table('historial_calificaciones')
    op.drop_table('historial_asistencia')
    # ### end Alembic commands ###
