"""tablas_iniciales

Revision ID: acf4b5a8f767
Revises: 
Create Date: 2026-08-01 05:22:25.344100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf4b5a8f767'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aulas',
    sa.Column('id_aula', sa.Integer(), nullable=False),
    sa.Column('nombre_aula', sa.String(length=50), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_aula')
    )
    op.create_index(op.f('ix_aulas_id_aula'), 'aulas', ['id_aula'], unique=False)
    op.create_table('materias',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nombre_materia', sa.String(length=120), nullable=True),
    sa.Column('clave_materia', sa.String(length=20), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_materia'),
    sa.UniqueConstraint('clave_materia')
    )
    op.create_index(op.f('ix_materias_id_materia'), 'materias', ['id_materia'], unique=False)
    op.create_table('periodos',
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('nombre_periodo', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_periodo')
    )
    op.create_index(op.f('ix_periodos_id_periodo'), 'periodos', ['id_periodo'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('correo_institucional', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'DOCENTE', 'TUTOR', name='rolenum'), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('token_recuperacion', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo_institucional'), 'usuarios', ['correo_institucional'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('administradores',
    sa.Column('id_administrador', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_administrador')
    )
    op.create_index(op.f('ix_administradores_id_administrador'), 'administradores', ['id_administrador'], unique=False)
    op.create_table('docentes',
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('numero_empleado', sa.String(length=20), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_docente'),
    sa.UniqueConstraint('numero_empleado')
    )
    op.create_index(op.f('ix_docentes_id_docente'), 'docentes', ['id_docente'], unique=False)
    op.create_table('planes_estudio',
    sa.Column('id_plan_estudio', sa.Integer(), nullable=False),
    sa.Column('nombre_plan', sa.String(length=120), nullable=True),
    sa.Column('id_periodo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodos.id_periodo'], ),
    sa.PrimaryKeyConstraint('id_plan_estudio')
    )
    op.create_index(op.f('ix_planes_estudio_id_plan_estudio'), 'planes_estudio', ['id_plan_estudio'], unique=False)
    op.create_table('tutores',
    sa.Column('id_tutor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('numero_empleado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tutor'),
    sa.UniqueConstraint('numero_empleado')
    )
    op.create_index(op.f('ix_tutores_id_tutor'), 'tutores', ['id_tutor'], unique=False)
    op.create_table('avisos',
    sa.Column('id_aviso', sa.Integer(), nullable=False),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('alcance', sa.String(length=50), nullable=True),
    sa.Column('id_referencia_alcance', sa.Integer(), nullable=True),
    sa.Column('urgente', sa.Boolean(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['administradores.id_administrador'], ),
    sa.PrimaryKeyConstraint('id_aviso')
    )
    op.create_index(op.f('ix_avisos_id_aviso'), 'avisos', ['id_aviso'], unique=False)
    op.create_table('grupos',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('nombre_grupo', sa.String(length=50), nullable=True),
    sa.Column('id_tutor', sa.Integer(), nullable=True),
    sa.Column('id_plan_estudio', sa.Integer(), nullable=True),
    sa.Column('carrera', sa.String(length=100), nullable=True),
    sa.Column('cuatrimestre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_plan_estudio'], ['planes_estudio.id_plan_estudio'], ),
    sa.ForeignKeyConstraint(['id_tutor'], ['tutores.id_tutor'], ),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_index(op.f('ix_grupos_id_grupo'), 'grupos', ['id_grupo'], unique=False)
    op.create_table('plan_materia',
    sa.Column('id_plan_materia', sa.Integer(), nullable=False),
    sa.Column('id_plan_estudio', sa.Integer(), nullable=True),
    sa.Column('id_materia', sa.Integer(), nullable=True),
    sa.Column('cuatrimestre_asignado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id_materia'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_plan_estudio'], ['planes_estudio.id_plan_estudio'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_plan_materia')
    )
    op.create_index(op.f('ix_plan_materia_id_plan_materia'), 'plan_materia', ['id_plan_materia'], unique=False)
    op.create_table('estudiantes',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('fotografia_url', sa.String(length=255), nullable=True),
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.Column('datos_socioeconomicos', sa.Text(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_estudiante')
    )
    op.create_index(op.f('ix_estudiantes_id_estudiante'), 'estudiantes', ['id_estudiante'], unique=False)
    op.create_index(op.f('ix_estudiantes_matricula'), 'estudiantes', ['matricula'], unique=True)
    op.create_table('horarios',
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.Column('id_materia', sa.Integer(), nullable=True),
    sa.Column('id_docente', sa.Integer(), nullable=True),
    sa.Column('id_aula', sa.Integer(), nullable=True),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', name='diasemanaenum'), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['id_aula'], ['aulas.id_aula'], ),
    sa.ForeignKeyConstraint(['id_docente'], ['docentes.id_docente'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id_materia'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_index(op.f('ix_horarios_id_horario'), 'horarios', ['id_horario'], unique=False)
    op.create_table('alertas',
    sa.Column('id_alerta', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('nivel_riesgo', sa.Enum('SIN_RIESGO', 'BAJO', 'MEDIO', 'ALTO', name='riesgoenum'), nullable=True),
    sa.Column('probabilidad', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('porcentaje_inasistencia', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('promedio_ponderado', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    op.create_index(op.f('ix_alertas_id_alerta'), 'alertas', ['id_alerta'], unique=False)
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_horario', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('estatus', sa.Enum('PRESENTE', 'AUSENTE', 'RETARDO', name='estatusasistenciaenum'), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_horario'], ['horarios.id_horario'], ),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_index(op.f('ix_asistencias_id_asistencia'), 'asistencias', ['id_asistencia'], unique=False)
    op.create_table('calificaciones',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_materia', sa.Integer(), nullable=True),
    sa.Column('id_periodo', sa.Integer(), nullable=True),
    sa.Column('parcial', sa.Integer(), nullable=True),
    sa.Column('valor', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('promedio_calculado', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id_materia'], ),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodos.id_periodo'], ),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_index(op.f('ix_calificaciones_id_calificacion'), 'calificaciones', ['id_calificacion'], unique=False)
    op.create_table('intervenciones',
    sa.Column('id_intervencion', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_tutor', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('acuerdos', sa.Text(), nullable=True),
    sa.Column('nivel_resolucion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_tutor'], ['tutores.id_tutor'], ),
    sa.PrimaryKeyConstraint('id_intervencion')
    )
    op.create_index(op.f('ix_intervenciones_id_intervencion'), 'intervenciones', ['id_intervencion'], unique=False)
    op.create_table('observaciones_conducta',
    sa.Column('id_observacion', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_docente', sa.Integer(), nullable=True),
    sa.Column('etiqueta', sa.String(length=50), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_docente'], ['docentes.id_docente'], ),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiantes.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_observacion')
    )
    op.create_index(op.f('ix_observaciones_conducta_id_observacion'), 'observaciones_conducta', ['id_observacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observaciones_conducta_id_observacion'), table_name='observaciones_conducta')
    op.drop_table('observaciones_conducta')
    op.drop_index(op.f('ix_intervenciones_id_intervencion'), table_name='intervenciones')
    op.drop_table('intervenciones')
    op.drop_index(op.f('ix_calificaciones_id_calificacion'), table_name='calificaciones')
    op.drop_table('calificaciones')
    op.drop_index(op.f('ix_asistencias_id_asistencia'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_alertas_id_alerta'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_horarios_id_horario'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_estudiantes_matricula'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_id_estudiante'), table_name='estudiantes')
    op.drop_table('estudiantes')
    op.drop_index(op.f('ix_plan_materia_id_plan_materia'), table_name='plan_materia')
    op.drop_table('plan_materia')
    op.drop_index(op.f('ix_grupos_id_grupo'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_avisos_id_aviso'), table_name='avisos')
    op.drop_table('avisos')
    op.drop_index(op.f('ix_tutores_id_tutor'), table_name='tutores')
    op.drop_table('tutores')
    op.drop_index(op.f('ix_planes_estudio_id_plan_estudio'), table_name='planes_estudio')
    op.drop_table('planes_estudio')
    op.drop_index(op.f('ix_docentes_id_docente'), table_name='docentes')
    op.drop_table('docentes')
    op.drop_index(op.f('ix_administradores_id_administrador'), table_name='administradores')
    op.drop_table('administradores')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo_institucional'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_periodos_id_periodo'), table_name='periodos')
    op.drop_table('periodos')
    op.drop_index(op.f('ix_materias_id_materia'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_aulas_id_aula'), table_name='aulas')
    op.drop_table('aulas')
    # ### end Alembic commands ###
